//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Access
{
    using System;
    using System.Collections.Generic;
    
    public partial class Historico_Pago
    {
        public int idPago { get; set; }
        public int idCliente { get; set; }
        public System.DateTime fechaPago { get; set; }
        public System.DateTime motoPagado { get; set; }
        public string notaOpcional { get; set; }
        public int idUsuario { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual Sys_Usuario Sys_Usuario { get; set; }
    }
}
