//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Access
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GimnasioEntities : DbContext
    {
        public GimnasioEntities()
            : base("name=GimnasioEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cliente> Cliente { get; set; }
        public virtual DbSet<Historico_Pago> Historico_Pago { get; set; }
        public virtual DbSet<Sys_Roll> Sys_Roll { get; set; }
        public virtual DbSet<Sys_Usuario> Sys_Usuario { get; set; }
    }
}
